from typing import Optional, TYPE_CHECKING
import pygame

from nightfall.client.ui.components.base_component import BaseComponent
from nightfall.client.ui.components.queue_components import BuildQueueComponent, UnitQueueComponent

if TYPE_CHECKING:
    # This block is only read by type checkers, not at runtime
    from nightfall.client.ui_manager import UIManager
    from nightfall.core.state.game_state import GameState

# Colors - It's good practice for components to define or import their own colors
C_GRAY = (50, 50, 50)
C_RED = (200, 0, 0)
C_GREEN = (0, 200, 0)
C_WHITE = (255, 255, 255)
C_YELLOW = (255, 215, 0)
C_LIGHT_GRAY = (150, 150, 150)

class ResourcePanelComponent(BaseComponent):
    def handle_event(self, event: pygame.event.Event, *args, **kwargs) -> Optional[dict]:
        return None # This panel is display-only

    def draw(self, screen: pygame.Surface, ui_manager: "UIManager", game_state: "GameState", city, production):
        resource_rect = ui_manager.resource_panel_rect
        pygame.draw.rect(screen, (30,30,30), resource_rect, border_radius=8)
        
        res_y = resource_rect.y + 15
        stats_x_offset = resource_rect.x + 220
        res = city.resources
        
        font_s = ui_manager.font_s
        
        # Helper to draw text
        def draw_text(text, pos, font=font_s, color=C_WHITE):
            surface = font.render(text, True, color)
            screen.blit(surface, pos)

        draw_text(f"Food: {res.food} (+{production.food if production else 0})", (resource_rect.x + 20, res_y))
        draw_text(f"Action Points: {city.action_points} / {city.max_action_points}", (stats_x_offset, res_y))
        res_y += 25
        draw_text(f"Wood: {res.wood} (+{production.wood if production else 0})", (resource_rect.x + 20, res_y))
        draw_text(f"Buildings: {city.num_buildings} / {city.max_buildings}", (stats_x_offset, res_y))
        res_y += 25
        draw_text(f"Iron: {res.iron} (+{production.iron if production else 0})", (resource_rect.x + 20, res_y))


class SidePanelComponent(BaseComponent):
    def __init__(self, ui_manager: "UIManager"):
        self.ui_manager = ui_manager
        self.font_m = ui_manager.font_m
        self.font_s = ui_manager.font_s
        
        # The panel owns its sub-components
        self.resource_panel = ResourcePanelComponent()
        self.build_queue_panel = BuildQueueComponent(ui_manager)
        self.unit_queue_panel = UnitQueueComponent(ui_manager)

    def handle_event(self, event: pygame.event.Event, game_state: "GameState", action_queue: list) -> Optional[dict]:
        # Delegate events to sub-components first
        action = self.build_queue_panel.handle_event(event, game_state, action_queue)
        if action: return action

        if event.type == pygame.MOUSEBUTTONDOWN and event.button == 1:
            # --- Handle Splitter Drag ---
            if self.ui_manager.splitter_rect.collidepoint(event.pos):
                self.ui_manager.is_dragging_splitter = True
                return None
            if self.ui_manager.queue_splitter_rect.collidepoint(event.pos):
                self.ui_manager.is_dragging_queue_splitter = True
                return None

            # --- Handle Button Clicks ---
            if self.ui_manager.buttons['exit_session'].collidepoint(event.pos):
                return {"type": "exit_session"}
            if self.ui_manager.buttons['end_day'].collidepoint(event.pos):
                return {"type": "end_day"}

        elif event.type == pygame.MOUSEBUTTONUP and event.button == 1:
            self.ui_manager.is_dragging_splitter = False
            self.ui_manager.is_dragging_queue_splitter = False

        elif event.type == pygame.MOUSEMOTION:
            if self.ui_manager.is_dragging_splitter:
                new_panel_width = self.ui_manager.screen_width - event.pos[0]
                self.ui_manager.update_side_panel_width(new_panel_width, action_queue)
            elif self.ui_manager.is_dragging_queue_splitter:
                self._handle_queue_splitter_drag(event, action_queue)

        return None # No action generated by the panel itself

    def _handle_queue_splitter_drag(self, event: pygame.event.Event, action_queue: list):
        total_y_start = self.ui_manager.resource_panel_rect.bottom + 10
        total_y_end = self.ui_manager.buttons['end_day'].top - 10
        total_height = total_y_end - total_y_start
        if total_height <= 0: return

        splitter_pos_relative = event.pos[1] - total_y_start
        max_content_height = 40 + (len(action_queue) * 30)
        clamped_splitter_pos = min(splitter_pos_relative, max_content_height)

        new_ratio = clamped_splitter_pos / total_height
        self.ui_manager.queue_split_ratio = max(0.05, min(0.95, new_ratio))
        self.ui_manager.update_queue_layouts(action_queue)

    def draw(self, screen: pygame.Surface, game_state: "GameState", city, production, action_queue):
        side_panel_rect = self.ui_manager.side_panel_rect
        screen.fill(C_GRAY, side_panel_rect)

        # Draw splitter
        splitter_color = C_YELLOW if self.ui_manager.is_dragging_splitter else C_LIGHT_GRAY
        pygame.draw.rect(screen, splitter_color, self.ui_manager.splitter_rect)

        if not city:
            screen.blit(self.font_m.render("No city selected.", True, C_WHITE), (side_panel_rect.x + 20, side_panel_rect.y + 20))
            return

        # Draw sub-components
        self.resource_panel.draw(screen, self.ui_manager, game_state, city, production)
        self.build_queue_panel.draw(screen, self.ui_manager, action_queue)
        self.unit_queue_panel.draw(screen, self.ui_manager, city)

        # Draw queue splitter
        splitter_color = C_YELLOW if self.ui_manager.is_dragging_queue_splitter else C_LIGHT_GRAY
        pygame.draw.rect(screen, splitter_color, self.ui_manager.queue_splitter_rect)

        # Draw elements owned by the panel itself (like headers and global buttons)
        screen.blit(self.font_m.render(f"City: {city.name}", True, C_WHITE), (side_panel_rect.x + 20, 20))
        screen.blit(self.font_m.render(f"Turn: {game_state.turn}", True, C_WHITE), (side_panel_rect.x + 20, 60))

        exit_rect = self.ui_manager.buttons['exit_session']
        pygame.draw.rect(screen, C_RED, exit_rect, border_radius=5)
        text_surf = self.font_s.render("Exit to Lobby", True, C_WHITE)
        screen.blit(text_surf, text_surf.get_rect(center=exit_rect.center))

        end_day_rect = self.ui_manager.buttons['end_day']
        pygame.draw.rect(screen, C_GREEN, end_day_rect, border_radius=5)
        text_surf = self.font_m.render("Ready (End Day)", True, C_WHITE)
        screen.blit(text_surf, text_surf.get_rect(center=end_day_rect.center))